name: Update Sitemap

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run sitemap script
        run: python generate_sitemap.py

      - name: Commit and push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "github-bot"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes"
          git push
